# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Niko Yu Blog
subtitle: 人生苦短，及时行乐
description: 肥宅
keywords: IT SSR 黑科技 程序员 web
author: Niko Yu
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.nikoyu.asia
root: /
permalink: :title.html
# permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  # - "source/tool/**"
  # - "source/qing/**"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude:
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Butterfly

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: 
     git    
    #  baidu_url_submitter  
  repo:
    - git@github.com:yujiajie01/yujiajie01.github.io.git
    # - https://github.com/yujiajie01/yujiajie01.github.io.git
    # - git@git.coding.net:hezhou/hezhou.coding.me.git
    - git@e.coding.net:nikoyu/nikoyu.coding.me.git
    # - https://e.coding.net/nikoyu/nikoyu.coding.me.git  
  branch: master



##douban
douban:
  user: nikoyu
  # builtin: true  
  builtin: false 
  movie:
    title: '人生就是一场轮回' 
    quote: 'Wheel of life' 

  game:
    title: '网瘾少年' 
    quote: "let's rethink our strategy"

  book:
    title: '指尖在纸张滑动的触感' 
    quote: 'The feel of a fingertip sliding on a piece of paper' 
  timeout: 10000 

# 百度map
Plugins:
- hexo-generator-baidu-sitemap
- hexo-generator-sitemap

baidusitemap:
    path: baidusitemap.xml
sitemap:
    path: sitemap.xml

#百度主动提交
baidu_url_submit:
  count: 100 # 提交最新的一个链接
  host: www.nikoyu.asia # 在百度站长平台中注册的域名
  token: N0sGMjeiqePEkcBl # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里

baidu_push: true

search:
  path: search.xml
  field: post

##algolia
algolia:
appId: 'VCXZW659UK'
apiKey: '6c1f6d54d44572781c305654447155ca'
adminApiKey: '43706998416a827a0444eff4ea8f90f7'
indexName: 'hexo-blog-search'
chunkSize: 5000
fields:
- title
- slug
- path
- content:strip

# MeingJS 支持 (3.0 新功能)
aplayer:
  meting: true
  asset_inject: false


# # hexo-tag-cloud
# tag_cloud:
#     textFont: Trebuchet MS, Helvetica
#     textColor: '#333'
#     textHeight: 25
#     outlineColor: '#E2E1D1'
#     maxSpeed: 0.1
